#!/usr/bin/env php
<?php
use Symfony\Component\Console\Application;

/** @var \Composer\Autoload\ClassLoader $loader */
$loader = require_once(__DIR__ . '/../vendor/autoload.php');
$loader->add('app', realpath(__DIR__ . '/../'));

$params = require(__DIR__ . '/config/params.php');

if (!empty($params['sentryDSN'])) {
    Raven_Autoloader::register();
    $client = new Raven_Client($params['sentryDSN']);
    $error_handler = new Raven_ErrorHandler($client);
    $error_handler->registerExceptionHandler();
    $error_handler->registerErrorHandler();
    $error_handler->registerShutdownFunction();
}

$app = require(__DIR__ . '/bootstrap.php');
$console = new Application();
require(__DIR__ . '/console.php');
$console->run();
